### ISSUE TITLE
testShacl.jar should be compiled on Travis

### ISSUE THREAD

**Issue by gaurav** [phyloref/phylo2owl#14]
Right now, it needs to be compiled locally because of a strange error on Travis (https://travis-ci.org/gaurav/phylo2owl/builds/177837977#L923). When we have more time, I'd like to look into this and figure out why it isn't working.

**Comment by gaurav** [comment]
I managed to get the [JAR file compiling successfully on Travis](https://github.com/gaurav/phylo2owl/tree/compile_testShacl_on_travis), and the ensuing JAR file is executable. However, when given a set of shapes to validate, it gives [an error message](https://travis-ci.org/gaurav/phylo2owl/builds/195744969#L1295):

> Exception in thread "main" java.lang.NoSuchMethodError: org.apache.jena.sparql.core.assembler.AssemblerUtils.registerModel(Lorg/apache/jena/rdf/model/Resource;Lorg/apache/jena/assembler/Assembler;)V
	at org.apache.jena.tdb.assembler.VocabTDB.init(VocabTDB.java:71)
	at org.apache.jena.tdb.assembler.VocabTDB.<clinit>(VocabTDB.java:64)
	at org.apache.jena.tdb.assembler.AssemblerTDB.init(AssemblerTDB.java:25)
	at org.apache.jena.tdb.TDB.init(TDB.java:251)
	at org.apache.jena.tdb.sys.InitTDB.start(InitTDB.java:29)
	at org.apache.jena.system.JenaSystem.lambda$init$1(JenaSystem.java:111)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.apache.jena.system.JenaSystem.forEach(JenaSystem.java:186)
	at org.apache.jena.system.JenaSystem.forEach(JenaSystem.java:163)
	at org.apache.jena.system.JenaSystem.init(JenaSystem.java:109)
	at org.apache.jena.rdf.model.ModelFactory.<clinit>(ModelFactory.java:49)
	at org.topbraid.spin.util.JenaUtil.createDefaultModel(JenaUtil.java:311)
	at org.topbraid.spin.util.JenaUtil.<clinit>(JenaUtil.java:74)
	at org.phyloref.phylo2owl.testShacl.main(testShacl.java:69)

I've figured out that the JAR files produced remotely and the one produced locally doesn't have exactly the same files in them, but they have all the files mentioned in the error message, so I'm still not sure what's causing this. Since we're fine producing JAR files locally for now, I'm going to hold off on this issue until it's needed.
